### ISSUE TITLE
TraceBack error with `config` file

### ISSUE THREAD

**Issue by unofficialdxnny** [Asssembly/Windows#1]
```cmd
Traceback (most recent call last):
  File "E:\GitHub\Assembly-Win\main.py", line 40, in <module>
    data = json.load(setup_type)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 2 (char 24)
```

**Comment by unofficialdxnny** [comment]
```json
{
    "setup_type": ""
},
{
    "gamer": "True_or_False"
}
```

This is invalid json...


```json
{
    "setup_type": "full",
    "gamer": "True_or_False"
}
```
